apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name:  mysqlclusters.mysql.middleware.harmonycloud.cn
  labels:
    MiddlewareCluster: mysqlcluster
spec:
  group: mysql.middleware.harmonycloud.cn
  names:
    kind: MysqlCluster
    listKind: MysqlClusterList
    plural: mysqlclusters
    shortNames:
      - mc
    singular: mysqlcluster
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: { }
