apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.middleware.harmonycloud.cn
  labels:
    MiddlewareCluster: mysqlbackup
    parent: mysqlcluster
spec:
  group: mysql.middleware.harmonycloud.cn
  names:
    kind: MysqlBackup
    listKind: MysqlBackupList
    plural: mysqlbackups
    shortNames:
      - mb
    singular: mysqlbackup
  scope: Namespaced
  version: v1alpha1
