apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlreplicates.mysql.middleware.harmonycloud.cn
spec:
  group: mysql.middleware.harmonycloud.cn
  names:
    kind: MysqlReplicate
    listKind: MysqlReplicateList
    plural: mysqlreplicates
    shortNames:
      - mr
    singular: mysqlreplicate
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
