global:
  repository: harbor.middleware.com/middleware
  middleware_controller:
    image: middleware-controller
    tag: v1.2.1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    nodeSelector: {}
  middlewarebackup_controller:
    image: middlewarebackup-controller
    tag: v1.0.0-test
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    nodeSelector: {}
