apiVersion: v1
kind: Service
metadata:
  name: zeus
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: http
    nodePort: 30288
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30299
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: zeus
  sessionAffinity: None
  type: ClusterIP